baseURL = 'https://zemelaar.blog/'
languageCode = 'nl-nl'
title = 'Zemelaar'
theme = 'hugo-bearblog'

enableRobotsTXT = true

[permalinks]
  blog = '/:slug/'

[params]
  description = 'Op het kaf na, de buitenste laag van de graankorrel'

[[menu.main]]
  name = 'Stukken'
  url = '/'
  weight = 10

[[menu.main]]
  name = 'Over'
  url = '/over/'
  weight = 20
