#!/usr/bin/env python3
"""Copy WordPress media from the archive into the Hugo static uploads tree.

Inputs:
    wordpress-data/media.tar
    migration/media-inventory.csv

Output:
    site/static/uploads/YYYY/MM/filename.ext

This script copies files using their existing WordPress upload-relative paths.
It does not rename, transform, resize, recompress, delete, or modify source media.
"""

from __future__ import annotations

import argparse
import csv
import shutil
import sys
import tarfile
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urlparse


@dataclass(frozen=True)
class MediaRow:
    post_id: str
    title: str
    attachment_url: str

    @property
    def expected_relative_path(self) -> str:
        parsed = urlparse(self.attachment_url)
        marker = "/wp-content/uploads/"
        if marker not in parsed.path:
            return ""
        return parsed.path.split(marker, 1)[1].lstrip("/")

    @property
    def output_relative_path(self) -> str:
        return self.expected_relative_path


def read_media_inventory(input_file: Path) -> list[MediaRow]:
    with input_file.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        required_fields = {"post_id", "title", "attachment_url"}
        missing_fields = required_fields - set(reader.fieldnames or [])
        if missing_fields:
            missing = ", ".join(sorted(missing_fields))
            raise ValueError(f"Missing required fields in media inventory: {missing}")

        rows: list[MediaRow] = []
        for row in reader:
            rows.append(
                MediaRow(
                    post_id=row.get("post_id", "").strip(),
                    title=row.get("title", "").strip(),
                    attachment_url=row.get("attachment_url", "").strip(),
                )
            )
        return rows


def safe_output_path(output_root: Path, relative_path: str) -> Path:
    if not relative_path:
        raise ValueError("Cannot build output path for empty relative path")

    relative = Path(relative_path)
    if relative.is_absolute() or ".." in relative.parts:
        raise ValueError(f"Unsafe media path: {relative_path}")

    output_path = output_root / relative
    resolved_root = output_root.resolve()
    resolved_output = output_path.resolve()

    if resolved_root not in [resolved_output, *resolved_output.parents]:
        raise ValueError(f"Output path escapes output root: {relative_path}")

    return output_path


def list_tar_files(archive: tarfile.TarFile) -> dict[str, tarfile.TarInfo]:
    files: dict[str, tarfile.TarInfo] = {}
    for member in archive.getmembers():
        if not member.isfile():
            continue
        normalized = member.name.replace("\\", "/").lstrip("./")
        files[normalized] = member
    return files


def find_member(expected_relative_path: str, tar_files: dict[str, tarfile.TarInfo]) -> tarfile.TarInfo | None:
    if not expected_relative_path:
        return None

    expected_relative_path = expected_relative_path.replace("\\", "/").lstrip("/")

    for name, member in tar_files.items():
        if name.endswith(expected_relative_path):
            return member

    expected_filename = Path(expected_relative_path).name
    filename_matches = [member for name, member in tar_files.items() if Path(name).name == expected_filename]
    if len(filename_matches) == 1:
        return filename_matches[0]

    return None


def copy_member(archive: tarfile.TarFile, member: tarfile.TarInfo, output_path: Path, overwrite: bool) -> str:
    if output_path.exists() and not overwrite:
        return "skipped_existing"

    output_path.parent.mkdir(parents=True, exist_ok=True)

    source = archive.extractfile(member)
    if source is None:
        return "missing_stream"

    with source, output_path.open("wb") as target:
        shutil.copyfileobj(source, target)

    return "copied"


def write_report(output_file: Path, copied: list[tuple[MediaRow, Path]], skipped_existing: list[tuple[MediaRow, Path]], missing: list[MediaRow]) -> None:
    output_file.parent.mkdir(parents=True, exist_ok=True)

    with output_file.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("# Media Copy Report\n\n")
        handle.write("Generated by `tools/copy-media-to-hugo.py`.\n\n")
        handle.write("## Summary\n\n")
        handle.write("| Metric | Count |\n")
        handle.write("|---|---:|\n")
        handle.write(f"| Copied files | {len(copied)} |\n")
        handle.write(f"| Skipped existing files | {len(skipped_existing)} |\n")
        handle.write(f"| Missing files | {len(missing)} |\n")
        handle.write("\n")

        if missing:
            handle.write("## Missing files\n\n")
            handle.write("| Post ID | Title | Expected path | Attachment URL |\n")
            handle.write("|---|---|---|---|\n")
            for row in missing:
                handle.write(f"| {row.post_id} | {escape_table(row.title)} | `{row.expected_relative_path}` | {row.attachment_url} |\n")
            handle.write("\n")

        handle.write("## Notes\n\n")
        handle.write("Files are copied to `site/static/uploads/` using their original WordPress upload-relative paths.\n\n")
        handle.write("This script does not rename media. Future readable media names should be handled separately through `migration/media-rewrite-map.csv`.\n")


def escape_table(value: str) -> str:
    return value.replace("|", "\\|")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Copy WordPress media archive files into Hugo static uploads")
    parser.add_argument("--inventory", default="migration/media-inventory.csv", help="Path to media inventory CSV")
    parser.add_argument("--archive", default="wordpress-data/media.tar", help="Path to WordPress media tar archive")
    parser.add_argument("--output-root", default="site/static/uploads", help="Hugo static uploads output directory")
    parser.add_argument("--report", default="migration/media-copy-report.md", help="Path to generated copy report")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite files that already exist in the output directory")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    inventory_file = Path(args.inventory)
    archive_file = Path(args.archive)
    output_root = Path(args.output_root)
    report_file = Path(args.report)

    if not inventory_file.exists():
        print(f"Error: media inventory not found: {inventory_file}", file=sys.stderr)
        return 1

    if not archive_file.exists():
        print(f"Error: media archive not found: {archive_file}", file=sys.stderr)
        return 1

    rows = read_media_inventory(inventory_file)

    copied: list[tuple[MediaRow, Path]] = []
    skipped_existing: list[tuple[MediaRow, Path]] = []
    missing: list[MediaRow] = []

    output_root.mkdir(parents=True, exist_ok=True)

    with tarfile.open(archive_file, "r:*") as archive:
        tar_files = list_tar_files(archive)

        for row in rows:
            member = find_member(row.expected_relative_path, tar_files)
            if member is None:
                missing.append(row)
                continue

            output_path = safe_output_path(output_root, row.output_relative_path)
            result = copy_member(archive, member, output_path, overwrite=args.overwrite)

            if result == "copied":
                copied.append((row, output_path))
            elif result == "skipped_existing":
                skipped_existing.append((row, output_path))
            else:
                missing.append(row)

    write_report(report_file, copied, skipped_existing, missing)

    print("Media copy complete")
    print()
    print(f"Inventory rows: {len(rows)}")
    print(f"Copied files: {len(copied)}")
    print(f"Skipped existing files: {len(skipped_existing)}")
    print(f"Missing files: {len(missing)}")
    print(f"Output root: {output_root}")
    print(f"Wrote: {report_file}")

    return 0 if not missing else 2


if __name__ == "__main__":
    raise SystemExit(main())
